services:
  MySQLdb:
    image: mysql:8.0
    container_name: isalvama-mysql
    restart: unless-stopped
    environment:
      # ESTA ES LA QUE FALTA Y ES OBLIGATORIA:
      MYSQL_ROOT_PASSWORD: ${PASSWORD_ROOT}

      # Opcional: Esto crea una base de datos automáticamente al arrancar
      MYSQL_DATABASE: ${DB_NAME}

      # Opcional: Esto crea un usuario normal (distinto a root)
      MYSQL_USER: usuario_proyecto
      MYSQL_PASSWORD: ${PASSWORD_ROOT}
    ports:
      - "3307:3306"
    volumes:
      - isalvama-mysql-volume:/var/lib/mysql

volumes:
  isalvama-mysql-volume:
